  on:
    push:
      branches:
        - main
    workflow_dispatch:

  
            
  jobs:
    workflow:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: |
              8.0.x  
        - name: Check env variable
          env:
            pgconn: ${{secrets.PGCONN}}
          run: if [ -v pgconn]; then echo "variable is set" && else echo "variable not set" && fi
        - name: Run, test and shutdown
          run: cd api && dotnet run & (sleep 30 && cd newsapitests && dotnet test) && kill -9 $(lsof -t -i:5000)
          

